version: '3.8'

services:
  database:
    image: postgres:17
    container_name: db-business-monitoring
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - aruba-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    container_name: business-monitoring
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SERVER_PORT_MANAGEMENT}:${SERVER_PORT_MANAGEMENT}"
    networks:
      - aruba-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      SERVER_PORT: ${SERVER_PORT}
      SERVER_PORT_MANAGEMENT: ${SERVER_PORT_MANAGEMENT}

volumes:
  db_data:

networks:
  aruba-network:
    driver: bridge