-- Create subscription_status table (reference data)
CREATE TABLE subscription_status (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                VARCHAR(50) NOT NULL,

    CONSTRAINT pk_subscription_status PRIMARY KEY (id),
    CONSTRAINT uk_subscription_status_code UNIQUE (code),
    CONSTRAINT ck_subscription_status_code CHECK (
        code IN ('ACTIVE', 'EXPIRED', 'PENDING_RENEWAL')
    )
);

-- Create sequence for customer_service_subscriptions
 CREATE SEQUENCE cust_sub_seq
     START WITH 1
     INCREMENT BY 30
     NO MINVALUE
     NO MAXVALUE
     CACHE 1;

-- Create customer_service_subscriptions table
CREATE TABLE customer_service_subscriptions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id         VARCHAR(100) NOT NULL,
    service_type        VARCHAR(100) NOT NULL,
    amount              DECIMAL(10,2) NOT NULL,
    activation_date     DATE NOT NULL,
    expiration_date     DATE NOT NULL,
    status_id           BIGINT NOT NULL,

    CONSTRAINT pk_customer_service_subscriptions PRIMARY KEY (id),
    CONSTRAINT fk_subscription_status
        FOREIGN KEY (status_id) REFERENCES subscription_status(id),
    CONSTRAINT ck_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_dates_valid CHECK (expiration_date >= activation_date)
);

-- Create indexes for better performance
CREATE INDEX idx_customer_subscriptions_customer_id
    ON customer_service_subscriptions(customer_id);

CREATE INDEX idx_customer_subscriptions_status_id
    ON customer_service_subscriptions(status_id);

CREATE INDEX idx_customer_subscriptions_expiration
    ON customer_service_subscriptions(expiration_date);